### ISSUE TITLE
MFP Product Zoom

### ISSUE THREAD

**Issue by GVFTW** [GVFTW/enhancements#1]
would like mfp to display gallery/thumbnails in popup like this
http://codepen.io/gyduxa/pen/YwKmzM

then zoom on 2nd click like this
http://codepen.io/dimsemenov/pen/kIorE

future proof with video integration while we are it?
http://codepen.io/dimsemenov/pen/jnohA

**Comment by EmilioTelevision** [comment]
peep game https://fitness-fashion-2.myshopify.com/products/blanket-jacket-posideon

**Comment by EmilioTelevision** [comment]
yea i had to disable zoom in order to do that. Also confused about the video link?

**Comment by GVFTW** [comment]
We're going to need some kind of zoom function. Doesn't have to be mfp, but the girls requested something so you can see the textures better. Any ideas?

Just wanted the flexibility embed a video in mfp gallery while we were working on it, but its not essential

**Comment by EmilioTelevision** [comment]
maybe some kind of magnify glass when you hover over in main window.

**Comment by GVFTW** [comment]
Anything out there with a click to zoom feature? Personally, i dont mind hover but when i was discussing with the girls neither of them liked it. 

Or maybe something like this on desktop where it can enlarge and hide the description?

https://www.saturdaysnyc.com/item/esquina-stipple-print-shirt-white

**Comment by EmilioTelevision** [comment]
still looking but im working on dropdown right now

**Comment by EmilioTelevision** [comment]
also your images aren't large enough to pull of your example

**Comment by GVFTW** [comment]
how large do they have to be? we upload everything at 1000x1320 (been doing it this way since I came on board), but I can get larger if needed.
