### ISSUE TITLE
Product Page - Style for Tablet

### ISSUE THREAD

**Issue by GVFTW** [GVFTW/enhancements#11]

**Comment by EmilioTelevision** [comment]
going to slowly start adding views
![image](https://cloud.githubusercontent.com/assets/3394886/16243754/c8edfa86-37c6-11e6-814a-12d3e0a12334.png)
![image](https://cloud.githubusercontent.com/assets/3394886/16243895/6e5335ea-37c7-11e6-896a-55e595c65c5b.png)
