### ISSUE TITLE
Product Page - Disable MFP on Carousel

### ISSUE THREAD

**Issue by GVFTW** [GVFTW/enhancements#14]
Please disable MFP at 590px wide. No need for popup since you can zoom in on image as is.

Want to avoid this -

<img width="315" alt="screen shot 2016-07-20 at 12 10 13 am" src="https://cloud.githubusercontent.com/assets/3649059/16974824/72131652-4e0e-11e6-8a9f-15304dc5d5e7.png">

**Comment by EmilioTelevision** [comment]
added disable on mobile to thescript

**Comment by GVFTW** [comment]
great closing issue
