### ISSUE TITLE
header - drop down menu fix

### ISSUE THREAD

**Issue by GVFTW** [GVFTW/enhancements#2]
check out the header here for example of how wed like to function  
http://www.rhone.com/

**Comment by EmilioTelevision** [comment]
the rhone example's menu is structured differently, did you want the menu list to have collections and dropdown to show collection image and description?

**Comment by GVFTW** [comment]
no we can keep structured as is
i was just referencing the animation, and how the links show up/disappear in sync. it looks/feels very sharp vs. ours is a bit clunky and doesn't resize when incentive window disappears.

**Comment by EmilioTelevision** [comment]
Its up and running, the rhone example uses a fixed height for their dropdown is not dynamic like ours https://fitness-fashion-2.myshopify.com/

**Comment by GVFTW** [comment]
looks great. 

is it possible to put a delay animation on the sub menu links (link 1 link 2 ... untitled) so they fade in once the header is fully dropped down?

also lets add some padding to the bottom edge of dropdown, so the last link isn't so close to the edge.

thank you!

**Comment by EmilioTelevision** [comment]
working on it

**Comment by EmilioTelevision** [comment]
added

**Comment by GVFTW** [comment]
love it, closing thread
