### ISSUE TITLE
related items grid - mobile vertical spacing

### ISSUE THREAD

**Issue by GVFTW** [GVFTW/enhancements#3]
vertical spacing on mobile

currently looks like 
<img width="342" alt="screen shot 2016-05-05 at 11 14 36 am" src="https://cloud.githubusercontent.com/assets/3649059/15047386/bd3773a4-12b2-11e6-882a-d9fa4a50153e.png">

should look like
<img width="329" alt="screen shot 2016-05-05 at 11 15 03 am" src="https://cloud.githubusercontent.com/assets/3649059/15047396/c69d5666-12b2-11e6-8072-a0a09aff4b98.png">

**Comment by EmilioTelevision** [comment]
![image](https://cloud.githubusercontent.com/assets/3394886/15136530/4cec3052-1650-11e6-97c5-a7103dda539b.png)

**Comment by GVFTW** [comment]
mobile looks perfect, love it

images look like they're on deskop, can we make them responsive? should resize like the featured products section on homepage

looks like
<img width="1440" alt="screen shot 2016-05-12 at 5 18 10 pm" src="https://cloud.githubusercontent.com/assets/3649059/15230817/b1857fca-1865-11e6-95bf-31b18c3968ff.png">

should look like
<img width="1438" alt="screen shot 2016-05-12 at 5 18 31 pm" src="https://cloud.githubusercontent.com/assets/3649059/15230830/c4a70f1a-1865-11e6-9856-39181bf17da0.png">

also, they should be bumping up right against wrapper
<img width="1195" alt="screen shot 2016-05-12 at 5 19 05 pm" src="https://cloud.githubusercontent.com/assets/3649059/15230848/d52c1664-1865-11e6-8d08-3955fa6221ff.png">

**Comment by EmilioTelevision** [comment]
fixed

**Comment by GVFTW** [comment]
looks great, closing thread
