### ISSUE TITLE
related items grid meta - add variant, remove .00 from price

### ISSUE THREAD

**Issue by GVFTW** [GVFTW/enhancements#4]
looks like 
<img width="148" alt="screen shot 2016-05-05 at 11 17 27 am" src="https://cloud.githubusercontent.com/assets/3649059/15047439/fc875420-12b2-11e6-80f1-9ef920eadc80.png">

should look like
<img width="155" alt="screen shot 2016-05-05 at 11 17 14 am" src="https://cloud.githubusercontent.com/assets/3649059/15047449/035fa5fe-12b3-11e6-9c9e-2c6afdefa60e.png">

**Comment by EmilioTelevision** [comment]
![image](https://cloud.githubusercontent.com/assets/3394886/15057219/c1009a48-12e3-11e6-8950-26dbaab0764f.png)

**Comment by GVFTW** [comment]
looks like the color variant in related items is currently matching the color variant on the product page it lives on. check it out ..

<img width="652" alt="screen shot 2016-05-05 at 6 14 06 pm" src="https://cloud.githubusercontent.com/assets/3649059/15058938/48b575d6-12ed-11e6-9769-77593b00038f.png">
<img width="648" alt="screen shot 2016-05-05 at 6 14 15 pm" src="https://cloud.githubusercontent.com/assets/3649059/15058935/44406ec0-12ed-11e6-8725-83516e7bea7c.png">

**Comment by EmilioTelevision** [comment]
yea its pulling the main products variant for some reason, been working on a solution
