### ISSUE TITLE
Search Results Page

### ISSUE THREAD

**Issue by GVFTW** [GVFTW/enhancements#5]
Looks like 
<img width="652" alt="screen shot 2016-06-21 at 4 14 30 am" src="https://cloud.githubusercontent.com/assets/3649059/16222564/ba68f5fc-3766-11e6-98ba-d35874e793c8.png">

Should look like
<img width="676" alt="screen shot 2016-06-21 at 4 14 46 am" src="https://cloud.githubusercontent.com/assets/3649059/16222568/c2084556-3766-11e6-862b-6585f2a8e482.png">

**Comment by GVFTW** [comment]
- no need for side bar / sort options
- clean up grid and meta data

**Comment by EmilioTelevision** [comment]
![image](https://cloud.githubusercontent.com/assets/3394886/16272863/685f15f4-386d-11e6-9391-41a3f5458132.png)

**Comment by EmilioTelevision** [comment]
![image](https://cloud.githubusercontent.com/assets/3394886/16281404/40c96ac4-3892-11e6-9238-87b8544faab2.png)

**Comment by GVFTW** [comment]
looks good. 2 edits and we're done
- let's go 2 columns wide on mobile (right now its single column)
- fix centering (looks like theres some padding-left on the thumbnails) and we're gravy (mobile and desktop)

<img width="968" alt="screen shot 2016-07-01 at 7 26 10 am" src="https://cloud.githubusercontent.com/assets/3649059/16520306/402c3a3e-3f5d-11e6-98da-9b5197022535.png">
<img width="305" alt="screen shot 2016-07-01 at 7 25 52 am" src="https://cloud.githubusercontent.com/assets/3649059/16520307/402ff368-3f5d-11e6-9934-ed4d8ad9b386.png">

**Comment by EmilioTelevision** [comment]
![screen shot 2016-07-01 at 12 12 21 pm](https://cloud.githubusercontent.com/assets/3394886/16527476/1fc103e2-3f85-11e6-8132-3be3da9ca71e.png)
![image](https://cloud.githubusercontent.com/assets/3394886/16527558/973371bc-3f85-11e6-9d6c-be600ba487d5.png)

**Comment by GVFTW** [comment]
mobile looks good
desktop for me looks different than you're screenshot. here's what i'm getting

<img width="1195" alt="screen shot 2016-07-01 at 1 16 35 pm" src="https://cloud.githubusercontent.com/assets/3649059/16528987/359ff0c0-3f8e-11e6-97ce-155f06012e0b.png">

should fit the wrapper edge to edge

**Comment by EmilioTelevision** [comment]
coolio 
![image](https://cloud.githubusercontent.com/assets/3394886/16532294/14ceeaa2-3f9f-11e6-83f2-dd81fbecc669.png)
