### ISSUE TITLE
Product Page - Mobile Carousel

### ISSUE THREAD

**Issue by GVFTW** [GVFTW/enhancements#7]
When you get to the final image, it auto scrolls back to beginning. Can we turn this off?

**Comment by EmilioTelevision** [comment]
went in and edited the script to prevent the loop

**Comment by GVFTW** [comment]
check out the product page on mobile - 
https://themes.shopify.com/themes/brooklyn/styles/brooklyn/preview

when you get to the last image, it scrolls in the same direction but shows you the first image again. 
this is how our carousel used to be, can we just revert to default to make it function like this again?

also thinking the dynamic image height may be causing our other issues with featured image height.

**Comment by EmilioTelevision** [comment]
the Slider controls the height and is a separate element than featured image, i have not edited or touched slider height, the image I did set to auto. It's height is determined by the wrapper, which in this case is the slider. When i recieved the theme, the slider was function as is now. I only touched the js once yesterday to turn off the loop (). While I in was there I tried all the other loop settings and it didn't. I downloaded the brooklyn and noticed their theme js contains all the javascript for the site while our theme has the slider and site separate

our site: 
![image](https://cloud.githubusercontent.com/assets/3394886/16528206/57557dc0-3f89-11e6-9482-c4d0a492d9b0.png)
brooklyn theme:
![image](https://cloud.githubusercontent.com/assets/3394886/16528226/84704038-3f89-11e6-9023-b921bc78a176.png)

The slider and theme js file have not been changed by me except for yesterday morning when i turned off the the continuous loop. Im not sure why the theme's are different but it makes it difficult to know what s breaking the slider

**Comment by GVFTW** [comment]
cool if we can't figure it out, let's just turn the auto return off. 

most important thing is that we have that auto slider return turned off, the girls at the office have been bitching about it to me for awhile now. we can figure out how to get it to function like in the example next time.

**Comment by EmilioTelevision** [comment]
cool, could troubleshoot to see if I can find whats breaking slider just need time. For now I stopped the continuous loop
