### ISSUE TITLE
Product Page - Mobile - Featured Image

### ISSUE THREAD

**Issue by GVFTW** [GVFTW/enhancements#8]
Sometimes main image loads slow or fails to load like this - 

![img_4906](https://cloud.githubusercontent.com/assets/3649059/16222934/b7a7dbc4-3768-11e6-8956-161b8d6803cc.PNG)

**Comment by EmilioTelevision** [comment]
I added min height to the slider image, haven't seen the bug since. let me know when you get a chance to review the rest of the git issues.

much thanks

**Comment by GVFTW** [comment]
getting some stretching now -

![img_5222](https://cloud.githubusercontent.com/assets/3649059/16520159/4151f33c-3f5c-11e6-8b71-fb1c852d9b66.PNG)

![img_5220](https://cloud.githubusercontent.com/assets/3649059/16520163/463c6d6e-3f5c-11e6-9f10-244b24615f82.PNG)

![img_5221](https://cloud.githubusercontent.com/assets/3649059/16520165/4a8a18b2-3f5c-11e6-9f57-aaafcf6789dc.PNG)

i've never seen this before!

**Comment by EmilioTelevision** [comment]
Check again, i think i removed what was causing the issue

**Comment by GVFTW** [comment]
works great, closing issue
