### ISSUE TITLE
Home Page - Style for Tablet

### ISSUE THREAD

**Issue by GVFTW** [GVFTW/enhancements#9]

**Comment by EmilioTelevision** [comment]
![image](https://cloud.githubusercontent.com/assets/3394886/16247627/a0c5e232-37d8-11e6-8e72-c9ad0e469f46.png)
![image](https://cloud.githubusercontent.com/assets/3394886/16247638/ac2a5c84-37d8-11e6-96e1-34b22b3d0077.png)
